### PR TITLE
Add interpolations support in default code - Fixes #156

### LINKED ISSUE #156: Habilitar el selector de interpolaciones para el default code
En kids funciona el selector de interpolaciones para el código extra, pero no aparece en el default. 

@flbulgarelli

### PR DESCRIPTION
**Pull request by rodri042**
Fixes #156

### CODE REVIEW

**Comment by flbulgarelli** [comment]
@fedescarpa and @nadiafinzi please review and merge

**Comment by flbulgarelli** [comment]
@fedescarpa ?

**Comment by fedescarpa** [comment]
I really like it.

Is possible to create xml and json files into assets folders in the repo. I dont like to use a gist.

**Comment by fedescarpa** [comment]
:+1: 
LGTM

**Pull request merged**
